version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - /mnt/nfs/homes/amyroshn/goinfre/database:/var/lib/postgresql/data
      #       - /Users/amyroshn/IdeaProjects/swingy/src/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./config/postgres.env
volumes:
  db:
    driver: local
